'use client';

import React, { useState } from 'react';

export default function DataSourceNote() {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="font-mono text-[10px] text-[#8B95AC] glass-panel p-2 max-w-sm">
      <div className="flex items-start gap-2">
        <button 
          onClick={() => setExpanded(!expanded)}
          className="text-[#FFC857] hover:text-[#EAEEF7] mt-0.5"
          aria-label="Toggle details"
        >
          {expanded ? '[-]' : '[+]'}
        </button>
        <div>
          <span className="text-[#EAEEF7] uppercase tracking-wider">SYNTHETIC DATA MODE</span> — All inputs generated by seeded simulators. Architecture mirrors IMD/INSAT/WWLLN/GFS operational systems.
        </div>
      </div>
      
      {expanded && (
        <div className="mt-2 pl-5 space-y-1 text-[#8B95AC]/80">
          <p>&gt; RADAR: Simulated IMD DWR network</p>
          <p>&gt; SAT: Simulated INSAT-3D IR/VIS</p>
          <p>&gt; LGT: Simulated WWLLN pulse data</p>
          <p>&gt; NWP: Simulated GFS boundary conditions</p>
        </div>
      )}
    </div>
  );
}
